### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: operation not permitted

### ISSUE THREAD

**Issue by onlymejosh** [teknologist/docker-webnut#1]
I am trying to use your image but am running into issues 

```
josh@mitsubishi:~/mitsubishi$ docker-compose up
Pulling nut (teknologist/webnut:)...
latest: Pulling from teknologist/webnut
Image docker.io/teknologist/webnut:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
3b8d91fe7572: Already exists
a3ed95caeb02: Already exists
dfc6505cfad4: Already exists
d037f43089a1: Already exists
4717f7a00ad0: Already exists
8a3b80faaa5d: Already exists
477523a5c87a: Already exists
94c9817feabb: Already exists
d1dd2f906fbd: Already exists
e223665f5c7e: Already exists
aa98bbb30a1e: Already exists
15471723cc6f: Already exists
Digest: sha256:12e3e09f7287bb9deddae792d9544d17b55a3bcbb44be95c3d9e663c29723947
Status: Downloaded newer image for teknologist/webnut:latest
webnut is up-to-date
Attaching to webnut
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
webnut | standard_init_linux.go:228: exec user process caused: operation not permitted
```

My compose file looks like

```
version: '3'
services:
  nut:
    image: teknologist/webnut
    container_name: webnut
    environment:
      - UPS_HOST=127.0.0.1
      - UPS_PORT=3493
      - UPS_USER=admin
      - UPS_PASSWORD=PASSWORD
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 6543:6543
networks:
  proxy:
    external: true
```

I had to create the proxy network but nothing else was done
